// `result_generated.rs` is produced by running:
//   flatc --rust -o src/schema src/schema/result.fbs
// Re-run that whenever result.fbs changes — unlike the protobuf side
// (which regenerates automatically via build.rs on every `cargo build`),
// the FlatBuffers bindings here are checked in and regenerated by hand.
#[allow(clippy::all, dead_code, unused_imports)]
mod result_generated;

pub use result_generated::query_cache::fb::{
    ResultRow, ResultRowArgs, ResultSet, ResultSetArgs,
};
